{{- if eq .Values.deploymentType "build" }}
apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  name: {{ include "openad-model.fullname" . }}
  labels:
    {{- include "openad-model.labels" . | nindent 4 }}
spec:
  tags:
    - name: "latest"
      from:
        kind: ImageStreamTag
        name: "{{ include "openad-model.fullname" . }}:latest"
{{- end }}
